/*
 * This file is generated by jOOQ.
 */
package _2fgenerated.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InitsTable implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  name;

    public InitsTable() {}

    public InitsTable(InitsTable value) {
        this.id = value.id;
        this.name = value.name;
    }

    public InitsTable(
        Integer id,
        String  name
    ) {
        this.id = id;
        this.name = name;
    }

    /**
     * Getter for <code>public.inits_table.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.inits_table.id</code>.
     */
    public InitsTable setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.inits_table.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.inits_table.name</code>.
     */
    public InitsTable setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final InitsTable other = (InitsTable) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InitsTable (");

        sb.append(id);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
