/*
 * This file is generated by jOOQ.
 */
package _2fgenerated;


import _2fgenerated.tables.InitsTable;
import _2fgenerated.tables.records.InitsTableRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<InitsTableRecord> INITS_TABLE_PKEY = Internal.createUniqueKey(InitsTable.INITS_TABLE, DSL.name("inits_table_pkey"), new TableField[] { InitsTable.INITS_TABLE.ID }, true);
}
