/*
 * This file is generated by jOOQ.
 */
package _2fgenerated;


import _2fgenerated.tables.InitsTable;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.inits_table</code>.
     */
    public static final InitsTable INITS_TABLE = InitsTable.INITS_TABLE;
}
